### PR TITLE
FEATURE: Relax version constraint for Neos 8 support

### PR DESCRIPTION
**Pull request by rolandschuetz**

### CODE REVIEW

**Comment by Sebobo** [comment]
What is the exact reason? I wanted to abandon this package.
Or why would you think it works better technically than the core version in 8.x?

**Comment by rolandschuetz** [comment]
It's the issue from https://github.com/neos/neos-ui/pull/2930
With the plugin it works, with the core it doesnt

**Comment by Sebobo** [comment]
Ok I see and remember now. Because the handling of non absolute resource Uris does not work depending on the environment, I refrained from supporting them in the core feature. I'll merge.

**Comment by rolandschuetz** [comment]
Thanks ❤️

**Pull request merged**
